


version: 2.1

jobs:
  build: 
    docker: 
      - image: circleci/node:latest
      - environment: 
          NAME: 'joshua'
    steps: 
      - checkout 
      - run:
          name: Command to execute
          command: ls -a
